server:
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/roadmap
    username: postgres
    password: su201314
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      write-dates-as-timestamps: false

logging:
  level:
    com.roadmap: DEBUG
    org.hibernate.SQL: DEBUG
