@echo off
setlocal EnableExtensions

REM =====================================================
REM  RoadMap - start TileServer-GL
REM  Requirements:
REM    - Node.js 16+
REM    - data\china.mbtiles generated by generate-tiles.bat
REM =====================================================

set "PROJECT_DIR=%~dp0.."
set "MBTILES=%PROJECT_DIR%\data\china.mbtiles"
set "CONFIG=%PROJECT_DIR%\tileserver\config.json"
set "PORT=8890"

echo =====================================================
echo  RoadMap - TileServer-GL
echo =====================================================
echo.

if not exist "%MBTILES%" (
    echo [ERROR] MBTiles file not found:
    echo         "%MBTILES%"
    echo.
    echo Run first:
    echo   scripts\generate-tiles.bat
    exit /b 1
)

if not exist "%CONFIG%" (
    echo [ERROR] TileServer config not found:
    echo         "%CONFIG%"
    exit /b 1
)

echo [INFO] Starting TileServer-GL...
echo [INFO] MBTiles: "%MBTILES%"
echo [INFO] Config : "%CONFIG%"
echo [INFO] Port   : %PORT%
echo [INFO] URL    : http://localhost:%PORT%
echo [INFO] Style  : http://localhost:%PORT%/styles/roadmap-basic/style.json
echo.

npx tileserver-gl --config "%CONFIG%" --port %PORT% --verbose
