@echo off
setlocal EnableExtensions

REM =====================================================
REM  RoadMap - start TileServer-GL
REM  Requirements:
REM    - Node.js 16+
REM    - data\china.mbtiles generated by generate-tiles.bat
REM =====================================================

set "PROJECT_DIR=%~dp0.."
set "MBTILES=%PROJECT_DIR%\data\china.mbtiles"
set "PORT=8080"

echo =====================================================
echo  RoadMap - TileServer-GL
echo =====================================================
echo.

if not exist "%MBTILES%" (
    echo [ERROR] MBTiles file not found:
    echo         "%MBTILES%"
    echo.
    echo Run first:
    echo   scripts\generate-tiles.bat
    exit /b 1
)

echo [INFO] Starting TileServer-GL...
echo [INFO] MBTiles: "%MBTILES%"
echo [INFO] Port   : %PORT%
echo [INFO] URL    : http://localhost:%PORT%
echo.

npx tileserver-gl --mbtiles "%MBTILES%" --port %PORT% --verbose
